### ISSUE TITLE
filtered query returning no hits

### ISSUE THREAD

**Issue by giorgiacek** [younginnovations/resourcecontracts-elasticsearch#1] opened 2015-10-21 10:20 UTC
Not very experienced with elastic search, but trying to run a filtered query, and I get no hits, but yesterday morning it used to work, how is that possible?

```
'{
"query": {
"filtered": {
 "query": {"term": { "signature_year": "2000"}},
  "filter": {
   "term": { "language": "english"}
      }
    }
  }
}'
```

(sorry for bad styling)

**Comment by adinuca** [comment] 2018-11-09 13:06
Closing as the issue is too old.

**Closed by adinuca** 2018-11-09 13:06 UTC
